"""5 sabiendo que ValueError es una excepción que se lanza cuando no podemos convertir una cadena de texto en un valor numérico, escriba una funcion get_int() que lea un valor entero del usuario y lo devualva, iterando mientras el valor no sea correcto. Intente resolver el ejercicio tanto de manera iterativa como recursiva"""